title: Kushal Navghare # your name (or website title) here
logo: "img/profile~1.png" # your photo (or logo) here
description:
  <br>
 Master's degree in Data Science from DePaul University.

theme: jekyll-theme-minimal
colors:
  crimson: '#900C3F'

footer: false