title: Kushal Navghare # your name (or website title) here
logo: "img/profile.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Accomplished Data Scientist skilled in advanced analytics and machine learning to solve complex business problems. Experienced in developing scalable solutions that drive growth and efficiency. Passionate about continuous learning and applying cutting-edge technologies.
  <br><br>
  Master's degree in Data Science from DePaul University.
  <br><br>

theme: jekyll-theme-minimal
colors:
  crimson: '#900C3F'

footer: false